sudo: required

language: c

compiler:
  - clang

install:
  - curl https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz > cmocka.tar.xz
  - tar -xvf cmocka.tar.xz
  - pushd cmocka-1.1.0
  - mkdir build
  - pushd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ..
  - make && sudo make install
  - popd
  - popd

script:
  - mkdir Build
  - cd Build
  - cmake .. && make
  - test/unit_tests
